### ISSUE TITLE
IndexRegistry does not update `currentOperatorIndex` when an operator is deregistered, in certain cases

### ISSUE THREAD

**Issue by wadealexc** [Layr-Labs/eigenlayer-middleware#126]
Came across this while working on documentation: 

https://github.com/Layr-Labs/eigenlayer-middleware/blob/ebe657e1167e59dc7959dfe11c8194b72bf9a347/src/IndexRegistry.sol#L99-L106

If `operatorId == lastOperatorId`, we never assign `currentOperatorIndex[operatorId]`.

To fix this, we can change `_popLastOperator` or add an `else` condition

**Comment by wadealexc** [comment]
Sidenote, I feel like I better understand what the `IndexRegistry` is doing, now that I've written a bunch of docs (esp about the BLSSigChecker).

And now going back through the `IndexRegistry`, I'm regretting the quantity of helper functions I added when I did refactoring a few months ago :grimacing:

**Comment by wadealexc** [comment]
Also sidenote, thinking about a fix for this issue, I'm remembering having had this conversation already.

I think the gist was that we don't have an "index does not exist" index - and that operators that have never registered have `currentOperatorIndex` of 0 by default... so we could set the value to 0 in this case, but that's also not technically correct, because there is actually an Operator with that index somewhere?

I'm not sure what the solution is, but maybe some context on how `currentOperatorIndex` is used offchain would help?

**Comment by wadealexc** [comment]
actually, noting here that `currentOperatorIndex` for the deregistering operator is actually just never updated, in any case -- same reasons as above, I guess. Not sure what we would give it, because there's no right answer.

**Comment by wadealexc** [comment]
Ideally we would have `INDEX_DOES_NOT_EXIST`, but in order to keep things consistent, it'd need to equal `0` so that never-registered operators have it by default. 

We'd then need to 1-index everything in the `IndexRegistry`, and that's definitely too much work to do at this stage.

**Comment by ChaoticWalrus** [comment]
We discussed some offline, but to summarize my views, I think this behavior is OK (pretty much for the reasons you've outlined above), just needs documentation on the proper usage -- I'd hate to see someone integrate with this code incorrectly.
