### ISSUE TITLE
Cleanup: unify typing of state variables in StakeRegistryStorage

### ISSUE THREAD

**Issue by wadealexc** [Layr-Labs/eigenlayer-middleware#127]
https://github.com/Layr-Labs/eigenlayer-middleware/blob/ebe657e1167e59dc7959dfe11c8194b72bf9a347/src/StakeRegistryStorage.sol#L30-L35

This is the only place in the middleware contracts where we use `[256]` to represent quorum information. I'd like to replace this with a mapping for consistency. I don't think it actually impacts a single thing, but if it this ends up breaking things it's fine to keep as-is.

**Comment by ChaoticWalrus** [comment]
I think this suggestion is fine.
obviously it's a breaking storage change for upgradeability purposes, so now seems like the right time to make the change 😅

**Comment by wadealexc** [comment]
> I think this suggestion is fine. obviously it's a breaking storage change for upgradeability purposes, so now seems like the right time to make the change 😅

Oh right, I didn't think about upgrading our Goerli contracts - would need to add some deprecated variables to make up the space.

**Comment by ChaoticWalrus** [comment]
> Oh right, I didn't think about upgrading our Goerli contracts - would need to add some deprecated variables to make up the space.

Aren't we already planning on redeploying because of other breaking storage layout / semantic changes? This strikes me as the last opportunity to reasonably make the change.

**Comment by wadealexc** [comment]
> > Oh right, I didn't think about upgrading our Goerli contracts - would need to add some deprecated variables to make up the space.
> 
> Aren't we already planning on redeploying because of other breaking storage layout / semantic changes? This strikes me as the last opportunity to reasonably make the change.

Will make sure I get a PR open for this today. I wanted to get the integration tests to a good state before I touched the contracts much more
