### ISSUE TITLE
Bug: register -> complete deregister -> register

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-middleware#19]
### Bug is on critical path to shipping eigenDA: please fix asap

Steps to reproduce:
- register operator with quorum 0
- deregister operator with quorum 0 (full deregistration)
- register operator with quorum 0
Get bug (from [this line](https://github.com/Layr-Labs/eigenlayer-middleware/blob/385e8dad21981e3d2651e31911875a43fcc44911/src/BLSRegistryCoordinatorWithIndices.sol#L407)):
```
"BLSRegistryCoordinatorWithIndices._registerOperatorWithCoordinator: operator already registered for some quorums being registered for"
```

Problem is that complete deregistration [doesn't push a new update](https://github.com/Layr-Labs/eigenlayer-middleware/blob/385e8dad21981e3d2651e31911875a43fcc44911/src/BLSRegistryCoordinatorWithIndices.sol#L515) to the `_operatorIdToQuorumBitmapHistory` mapping (compare to the [partial deregistration branch](https://github.com/Layr-Labs/eigenlayer-middleware/blob/385e8dad21981e3d2651e31911875a43fcc44911/src/BLSRegistryCoordinatorWithIndices.sol#L503)) and the register function [checks the previous quorumbitmap update](https://github.com/Layr-Labs/eigenlayer-middleware/blob/385e8dad21981e3d2651e31911875a43fcc44911/src/BLSRegistryCoordinatorWithIndices.sol#L407), so it actually lands on the quorumbitmap of when the operator was registered.

The easiest way to fix this is prob just to add an update even when doing a full deregistration, but there might be another (better?) way to do this, so opening this issue.

### Action Items
- [ ] decide on best way to fix this bug
- [ ] fix bug
- [ ] write a new test to test register->deregister->register

**Comment by shrimalmadhur** [comment]
Is EigenDA using this repo or still pointing to eigenlayer-contracts repo. If it's still using eigenlayer-contracts repo, please make the change in that one too. Thanks

**Comment by stevennevins** [comment]
@shrimalmadhur I talked to @0x0aa0 this am, and he's going to move over EigenDA to this repo today
