### ISSUE TITLE
Add a flag to turn off churner

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-middleware#218]
Some AVS teams don't want to run a churner, either because they don't want to deal with the offchain complexity, or because they want permissionless ejection (operator entering can kick any operator out, as long as that opertor getting ejected has stake < avg operator stake).

Could we add a feature flag `requireChurnerSignatures` or something in the contract so that the ejection logic wouldn't require a churner signature when the feature flag is set to false?

**Comment by wadealexc** [comment]
I don't think we should add any code (especially not to the RegistryCoordinator) at this point

This is definitely something people will want, but I'm not sure a feature flag is the right way to go about it -- AVS teams are better off forking our contracts and modifying them themselves FOR NOW

Eventually we'll get better at building generally-applicable middleware contracts and we can implement this without bloating bytecode and adding complexity to everyone's codebase.

**Comment by stevennevins** [comment]
Closing per the above comment
