### ISSUE TITLE
Add explanations above commented out slasher integration code

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-middleware#27]
We decided to leave slasher integration out of the upcoming M2 testnet deployment.
However, we have only reflected that choice by commenting out all the places where slasher calls are made.
Some of them have a TODO comment, for eg
https://github.com/Layr-Labs/eigenlayer-middleware/blob/f9c6508c85d971de133498aef29b454faba70d9c/src/StakeRegistry.sol#L119

Others are simply commented without comments, such as https://github.com/Layr-Labs/eigenlayer-middleware/blob/f9c6508c85d971de133498aef29b454faba70d9c/src/BLSRegistryCoordinatorWithIndices.sol#L381

Could we be consistent about these messages. Would be nice to have a single standardized message. This would help code readability, would make it easier to find all these instances when we do want to reenable the slasher, and would make it easier for the AVS team to communicate with external AVS devs the choices that are currently being made.

**Comment by stevennevins** [comment]
https://github.com/Layr-Labs/eigenlayer-middleware/pull/36

**Comment by samlaf** [comment]
@stevennevins #36 was merged, I think we can close this? 
If you add "Closes #PR_NUMBER" somewhere in the description of the PR, it'll automatically close linked issues.
