### ISSUE TITLE
Track network deployment addresses

### ISSUE THREAD

**Issue by NimaVaziri** [Layr-Labs/eigenlayer-middleware#46]
We want to track what contracts have been deployed to which networks so a configuration diff to the deployment script will be needed.

**Comment by stevennevins** [comment]
https://github.com/Layr-Labs/eigenlayer-middleware/pull/47

**Comment by samlaf** [comment]
@stevennevins please don’t close issues before the PR is actually merged. 

Also what we need is slightly different. We want to track exactly which commit of the contracts was deployed, not only the address and name of the contract.

we have multiple parallel deployments of the contracts right now on goerli (few for eigenDA, some for inc-sq, etc). Ideally the deployment output json would contain the hit commit that was deployed, but not sure how easy it is to get that from forge json methods.

**Comment by samlaf** [comment]
Closing as out of scope. We've also found other ways to do integration testing, and it seems everyone is fine with tracking deployment addresses in a README and/or excel sheet and updating those by hand, so I guess we'll go with that (I still find it weird and bug prone personally, but don't have time/energy/understanding of current method to investigate further, so will leave that to someone else who does).
