### ISSUE TITLE
Use the relative import path

### ISSUE THREAD

**Issue by cool-develope** [Layr-Labs/eigenlayer-middleware#77]
## Context

When import the repo as a submodule in foundry, the solidity does not understand the import path.
For example, [here](https://github.com/Layr-Labs/eigenlayer-middleware/blob/bee1c9f38862c08c413e2e1a1db97cc56ab50f14/src/VoteWeigherBase.sol#L6)
When compile the master project, it is trying to find the above path `import "src/VoteWeigherBaseStorage.sol";` on the main repo and it is failing.

**Comment by cool-develope** [comment]
To resolve it, we are using the customized remapping like `src/=lib/eigenlayer-middleware/src/` kind of a hacky solution 😮‍💨

**Comment by stevennevins** [comment]
@cool-develope Seems like a good quality-of-life improvement. When you do `forge remappings`, what foundry infer the remapping for eigenlayer-middleware to be without the customized remapping?
