### ISSUE TITLE
Test: RegistryCoordinator unit tests

### ISSUE THREAD

**Issue by 8sunyuan** [Layr-Labs/eigenlayer-middleware#91]
## Description
Lot of refactoring with this contract in particular, could also implement these tests after changes involving removal of the PubkeyCompendium and new operator registration flow. Mock contracts for the registry contracts should also be setup for testing functions here such as `_registerOperator`, `_deregisterOperator`, `updateOperators`

### Action Items
- [ ] Refactor test file according to our testing doc with mocks for registry contracts https://docs.google.com/document/d/107Wn4cVjSOTng1T72TWhhzswj1Afw4Dz7fUXQWqzLT0/edit?usp=sharing
- [ ] Generate tree file to layout branch execution
- [ ] Identify and add missing test coverage
- [ ] Create PR and get review

**Comment by ChaoticWalrus** [comment]
starting some work on this. putting together a draft tree diagram first

**Comment by ChaoticWalrus** [comment]
PR is here (currently marked as a draft): https://github.com/Layr-Labs/eigenlayer-middleware/pull/121

**Comment by ChaoticWalrus** [comment]
The relevant PR was merged!
Closing this out.
